api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        xml:      ['application/xml', 'text/xml']
        html:     ['text/html']